Update german translation [2/2]
solus-project/package-management pull request #27
Opened 2018-09-21 08:34 UTC by EruIluvatar

Some more typos popped up when using hunspell on it.
Sorry for the inconvenience...

2018-09-22 08:43 UTC, JoshStrobl requested changes

2018-09-22 08:43 UTC, JoshStrobl commented on po/de.po
> +msgstr "Starte den pisi build Vorgang ohne die extra debug Information anzuzeigen"
No this should lowercased.

2018-09-24 08:18 UTC, EruIluvatar commented on po/de.po
> +msgstr "Starte den pisi build Vorgang ohne die extra debug Information anzuzeigen"
should be fine now

2021-03-22 19:53 UTC, JoshStrobl commented
1. The repo has since been moved to a different org.
2. eopkg is frozen as we're building a new package manager.

2021-03-22 19:53 UTC, closed without merging